const CartActionTypes = {
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  INCREASE_ITEM: 'INCREASE_ITEM',
  DECREASE_ITEM: 'DECREASE_ITEM',
  CLEAR_CART: 'CLEAR_CART',
  ADD_TO_TOTAL: 'ADD_TO_TOTAL',
  CLEAR_TOTAL: 'CLEAR_TOTAL',
  CALC_ORDER_TOTAL: 'CALC_ORDER_TOTAL',
  CALC_TAX: 'CALC_TAX'
}

export default CartActionTypes